spring.application.name=boitenoire
spring.data.mongodb.database=pigeon
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/pigeon
spring.mongodb.database=pigeon
spring.mongodb.uri=mongodb://127.0.0.1:27017/pigeon